# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'docs_download.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DocsDownload(object):
    def setupUi(self, DocsDownload):
        DocsDownload.setObjectName("DocsDownload")
        DocsDownload.resize(801, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:/Users/Dubito/Desktop/1634396985874.jpeg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        DocsDownload.setWindowIcon(icon)
        DocsDownload.setAccessibleName("")
        DocsDownload.setAccessibleDescription("")
        self.label = QtWidgets.QLabel(DocsDownload)
        self.label.setGeometry(QtCore.QRect(10, 50, 111, 30))
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(DocsDownload)
        self.lineEdit.setGeometry(QtCore.QRect(130, 50, 651, 30))
        self.lineEdit.setStyleSheet("")
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(DocsDownload)
        self.label_2.setGeometry(QtCore.QRect(10, 90, 111, 30))
        self.label_2.setObjectName("label_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(DocsDownload)
        self.lineEdit_2.setGeometry(QtCore.QRect(130, 90, 481, 30))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.toolButton_2 = QtWidgets.QToolButton(DocsDownload)
        self.toolButton_2.setGeometry(QtCore.QRect(630, 90, 151, 30))
        self.toolButton_2.setObjectName("toolButton_2")
        self.toolButton_5 = QtWidgets.QToolButton(DocsDownload)
        self.toolButton_5.setGeometry(QtCore.QRect(400, 150, 130, 30))
        self.toolButton_5.setObjectName("toolButton_5")
        self.toolButton_3 = QtWidgets.QToolButton(DocsDownload)
        self.toolButton_3.setGeometry(QtCore.QRect(250, 150, 130, 30))
        self.toolButton_3.setStyleSheet("background-color: rgb(85, 170, 255);\n"
"color: rgb(255, 255, 255);\n"
"border: 0;")
        self.toolButton_3.setObjectName("toolButton_3")
        self.textBrowser = QtWidgets.QTextBrowser(DocsDownload)
        self.textBrowser.setGeometry(QtCore.QRect(0, 210, 801, 391))
        self.textBrowser.setObjectName("textBrowser")
        self.label_3 = QtWidgets.QLabel(DocsDownload)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 111, 30))
        self.label_3.setObjectName("label_3")
        self.radioButton = QtWidgets.QRadioButton(DocsDownload)
        self.radioButton.setGeometry(QtCore.QRect(130, 10, 75, 30))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(DocsDownload)
        self.radioButton_2.setGeometry(QtCore.QRect(230, 10, 101, 30))
        self.radioButton_2.setObjectName("radioButton_2")

        self.retranslateUi(DocsDownload)
        QtCore.QMetaObject.connectSlotsByName(DocsDownload)

    def retranslateUi(self, DocsDownload):
        _translate = QtCore.QCoreApplication.translate
        DocsDownload.setWindowTitle(_translate("DocsDownload", "文献一键下载器 - By: Dubito"))
        self.label.setText(_translate("DocsDownload", "文献资料链接："))
        self.label_2.setText(_translate("DocsDownload", "文件保存位置："))
        self.toolButton_2.setText(_translate("DocsDownload", "选择文件夹"))
        self.toolButton_5.setText(_translate("DocsDownload", "查看源码"))
        self.toolButton_3.setText(_translate("DocsDownload", "开始下载"))
        self.label_3.setText(_translate("DocsDownload", "文献下载网站："))
        self.radioButton.setText(_translate("DocsDownload", "豆丁网"))
        self.radioButton_2.setText(_translate("DocsDownload", "道客巴巴"))
